name: 'badge-generator'
description: 'Generate and save custom Shields.io badges directly from your GitHub Actions workflow.'

inputs:
  name:
    description: 'Text displayed on the right side of the badge (e.g. "98.7%").'
    required: true

  prefix:
    description: 'Text displayed on the left side of the badge (label). Optional.'
    required: false
    default: ''

  icon:
    description: 'Optional icon/logo name supported by Shields.io.'
    required: false
    default: ''

  color:
    description: 'Badge background color (e.g. green, blue, #ffaa00).'
    required: false
    default: 'blue'

  style:
    description: 'Badge style (e.g. flat, flat-square, plastic, for-the-badge).'
    required: false
    default: 'flat'

  path:
    description: 'File path where the generated badge will be saved (e.g. badges/coverage.svg).'
    required: true

  labelColor:
    description: 'Optional background color for the left-side label.'
    required: false
    default: ''

  logoColor:
    description: 'Optional color for the logo icon.'
    required: false
    default: ''

  link:
    description: 'Optional link or comma-separated links to embed in the badge.'
    required: false
    default: ''

  cacheSeconds:
    description: 'Optional cache duration in seconds for the badge.'
    required: false
    default: ''

runs:
  using: 'node20'
  main: 'dist/index.js'
